### ISSUE TITLE
Compiling Azure Sheep mod

### ISSUE THREAD

**Issue by LAGonauta** [malortie/halflife#15]
Hello, I am the developer of MetaAudio (https://github.com/LAGonauta/metahook/), an OpenAL audio plugin for GoldSrc.
I found a reproducible bug in the plugin that makes Azure Sheep crash in hl.dll (according to Visual Studio debugger), however I do not have the necessary debug symbols. I tried to compile the mod from your branch however I noticed there is no solution file for it and I wasn't able to create one myself... Kept getting 1000+ errors.

How does one compile the mods? Thanks.

The issue in my repository: https://github.com/LAGonauta/metahook/issues/2

**Comment by malortie** [comment]
Please read the following [blog post](https://www.moddb.com/members/malortie/blogs/half-life-1-steampipe-patches-to-be-archived).

The original mod has been reverse engineered by a team, which led to source code being rewritten and therefore resulted in closer if not exact behavior of the original mod entities, so I recommend that you check [their project](https://github.com/FWGS/hlsdk-xash3d/tree/asheep).

I am also in the process of restructuring the source code of my SteamPipe patches. I currently have a plan to move source code of each Half-Life SteamPipe patch to it's own repository and provide CMake support eventually, but it is impossible for me to know if and when this will be done.

**Comment by malortie** [comment]
Please see the [following commit](https://github.com/malortie/halflife/commit/8978602ed5056e2a4f51de2292cd13f0e94bacf7).

It appears I uploaded the Visual Studio projects a day after you opened the issue. It might be possible that I forgot to let you know.

Both projects were made using Visual Studio 2017, but I was able to compile them in Visual Studio 2019. I played through the entire mod and it seems to work.

In addition, I found a few bugs, for which I will try to look into when I'll find sufficient spare time.

**Comment by malortie** [comment]
@LAGonauta Please, can you test the project files and close the issue if they work ?

**Comment by LAGonauta** [comment]
Sorry, I forgot about this issue. Everything seems to work, thanks!
