### ISSUE TITLE
[Opposing Force] Project files were not updated to match restructured folder structure

### ISSUE THREAD

**Issue by SamVanheer** [malortie/halflife#16]
The last commit in branch `branch-malortie-op4` restructured the folders to separate Opposing Force specific changes to its own set of files, however the project files were not updated to match these changes. In order to compile the projects the file paths need to be corrected.

**Comment by malortie** [comment]
@SamVanheer 

Hello,

Yes, I am aware of this. Somehow, I ended up being too lazy for performing simple tasks such as updating VC projects, well at least when it comes to uploading source code for my steampipe patches and other experiments such as this attempt to code Opposing force from scratch.

Lately, I had a lack of motivation to work on SteamPipe related patches for Half-Life 1 & 2 mods,  but I could look into updating the VS projects, at least for the Opposing Force branch. 

Ideally, I should also update projects in every mod branch from this repository.

**Comment by malortie** [comment]
@SamVanheer 

Hello,

I had to make a few fixes to make the source code compilable. There were places in the source code "see diff in commit below"  with references to incomplete stuff, so I simply removed them. I committed project files for compiling the source code found in the "gearbox" folder. Visual Studio 2017 is needed to compile both projects. I tested it and it should have everything required to successfully build both client and game (server) DLLs. I also tested it in game and it works for what the current state of the source code is. 

Please understand that this is not a complete project and there are many missing features.

Here is a link to the commit.
https://github.com/malortie/halflife/commit/6c95ac437a0b0c3487fe73fce566b9d1f3db62d7

If you do approve the latest commit, please close this issue.
