### ISSUE TITLE
Android port

### ISSUE THREAD

**Issue by a1batross** [malortie/halflife#4]
I see you have sources of some mods. What do you think about Linux & Android port of it?

**Comment by malortie** [comment]
@a1batross 

These are not official sources of those mods. This is code to emulate those mods, which I try to reproduce to make it compatible with the latest versions of Steam pipeline.

Currently, I have personal matters to attend, so I cannot work on it for now. Nevertheless, you are welcome to try to improve and contribute, I see no problem in attempting a linux/android port, however I will only attend to these requests when I will have the time.

**Comment by a1batross** [comment]
Yes, I see that this is not official.
I just want to know which branch for which game and how it compatible

Seems that from op4 few weapons and monsters are implemented. Good job. :)

02.09.2015 22:54 пользователь "Marc-Antoine Lortie" <
notifications@github.com> написал:
>
> @a1batross
>
> These are not official sources of those mods. This is code to emulate
those mods, which I try to reproduce to make it compatible with the latest
versions of Steam pipeline.
>
> Currently, I have personal matters to attend, so I cannot work on it for
now. Nevertheless, you are welcome to try to improve and contribute, I see
no problem in attempting a linux/android port, however I will only attend
to these requests when I will have the time.

**Comment by malortie** [comment]
@a1batross 

Seeing as you are interested in these projects, I made you a contributor, so that you will be able to make changes without requesting permissions. I encourage you, along with other interested people, to provide feedback, make suggestions. Constructive criticism is very helpful and appreciated.

**Comment by mittorn** [comment]
Are there any makefiles/ project files?
I have made some changes and built an android app, but it seems that some scripts are broken.

**Comment by JoelTroch** [comment]
There is already an Androod port, check SDLash3D

**Comment by a1batross** [comment]
@JoelTroch 
lol, Joel. 
He is from SDLash3D too. :)

**Comment by JoelTroch** [comment]
@a1batross Sorry, university is killing my brains, I should get some sleep ^^

**Comment by a1batross** [comment]
@JoelTroch yes, sleeping is important. :)
