### ISSUE TITLE
how to enable host_framerate cvar with multiplayer

### ISSUE THREAD

**Issue by headshoter** [malortie/halflife#6]
i'm trying to do a Slow Motion effect, and i see HL have a cvar "host_framerate" that does the effect, but it only works on single player with sv_cheats 1.

seems to be an engine cvar, so i can't find that cvar on sdk, but somewhere that i can't see, singleplay_gameroules seems to enable that cvar. i want to do the same in multiplay_gameroules, is there a way to do it?

if you want to test, just put sv_cheats in console, start a singleplay match and put host_framerate 0.002 in console, enjoy the slow motion effect

hope you can help.

**Comment by malortie** [comment]
@headshoter

Despite forcing the framerate to 0.002 in mutliplayer_gamerules, 
framerate still remains unchanged.

This is something which I suppose, can't be changed unless having
access to the engine code itself.

**Comment by JoelTroch** [comment]
@malortie The Specialist is a MP mod that has a slow motion effect and they don't have access to the engine itself.

I think they play with all the thinking timings in order to achieve that effect in MP but I'm not sure.

**Comment by headshoter** [comment]
yup, I'm trying to do the same effect than The Specialists one.

it's supposed to somewhere, singleplay_gameroules enables that, or at least they make the engine "know" that you are playing singleplayer.

@JoelTroch yup, i thinked the same than you, but what timmings exactly they change?
seems to be they can change timing on certain players, maybe player pev->framerate?

thanks for help dudes.

**Comment by malortie** [comment]
@headshoter

As @JoelTroch explained, and I also was thinking the same.

You would need to share a common variable between client and server and
apply this to every portion involved with framerate.

Other than this, I do not see how this could be accomplished, without
having a license to the GoldSource engine.

**Comment by a1batross** [comment]
From Xash3D code:
`if( host_framerate->value > 0 && ( Host_IsLocalGame()))
{
	float fps = host_framerate->value;
	if( fps > 1 ) fps = 1.0f / fps;
	host.frametime = fps;
}
`

where is `Host_IsLocalGame()`:
`qboolean Host_IsLocalGame( void )
{
	if( host.type != HOST_DEDICATED )
	if( CL_Active() && SV_Active() && CL_GetMaxClients() == 1 )
		return true;
	return false;
}`

It just checks for maxplayers. So in multiplayer, where is maxplayers by defintion is higher than 1, it's isn't possible. Also, this is just isn't good way, because host_framerate locks FPS on specified rate. Just imagine, that your mod will run on system, where engine can render more than 1 / host_framerate frames per second.

**Comment by JoelTroch** [comment]
I agree with @a1batross , changing `host_framerate` to make a slow motion effect is a hack. If the mod was singleplayer, you wouldn't care about the `maxplayers` thingy but since you are making a multiplayer mode it's quite critical. That's why I suggested to "play" with the think timings.

**Comment by a1batross** [comment]
@JoelTroch Not only think timings. There is will be also player movement changes, weapon timings, tempents(particles, etc) timings.

For Source there is better feature -- `host_timescale`. But it require sv_cheats too.

**Comment by malortie** [comment]
I am going to close this issue, as this is unrelated to a bug or "Half-Life 1 SteamPipe patches" source code within the current repository.
