### ISSUE TITLE
Multiple instances of 'abs':ambiguous call to overloaded function

### ISSUE THREAD

**Issue by Combine12** [malortie/halflife#9]
Trying to build unmodified code in VS2015, this error appears about 9 times.

Line 265, roach.cpp:
`if ( pSound && abs( pSound->m_vecOrigin.z - pev->origin.z ) <= 3 )`

Line 2075, player.cpp:
`if (abs(gpGlobals->time - m_tbdPrev) < 2.0)`

Line 1129, plats.cpp:
`flpitch = TRAIN_STARTPITCH + (abs(pev->speed) * (TRAIN_MAXPITCH - TRAIN_STARTPITCH) / TRAIN_MAXSPEED);`

Line 599, func_break.cpp:
`fvol = RANDOM_FLOAT(0.85, 1.0) + (abs(pev->health) / 100.0);`

Line 553, bmodels.cpp:
`vecCur = abs(vecAVel.x != 0 ? vecAVel.x : (vecAVel.y != 0 ? vecAVel.y : vecAVel.z));`

Line 559, bmodels.cpp:
`vecFinal = abs(vecFinal);`

Lines 595-597, bmodels.cpp:
```
if (	abs(vecAVel.x) >= abs(pev->movedir.x * pev->speed)	&&
	abs(vecAVel.y) >= abs(pev->movedir.y * pev->speed)	&&
	abs(vecAVel.z) >= abs(pev->movedir.z * pev->speed) );
```

**Comment by malortie** [comment]
@Combine12 

Are you using my [VS 2015 branch](https://github.com/malortie/halflife/tree/branch-malortie-vs-2015) with fixed errors/warnings?

A few months ago, I also updated this branch to disable several warnings I did not notice.

I believe the solution should still compile without any problem.

Please, let me know.

**Comment by fuzun** [comment]
Change abs to fabs and try.

**Comment by Combine12** [comment]
Oh damnit! I'm an absolute fool for not noticing the different branches! The VS2015 branch compiles fine, so sorry for my stupidity!
